soc: qcom: event_timer.c: Fix Build after commit ef2e64035f074bfeef14c28347aaec0b486a9e9f
../drivers/soc/qcom/event_timer.c:54:3: error: field designator 'head' does not refer to any field in type 'typeof(struct timerqueue_head)' (aka 'struct timerqueue_head')
        .head = RB_ROOT,
         ^
1 error generated.

../drivers/soc/qcom/event_timer.c:55:3: error: fieldvdesignator 'next' does not refer to any field in type 'typeof(struct timerqueue_head)' (aka 'struct timerqueue_head')
	.next = NULL,
         ^
1 error generated.

Signed-off-by: GhostMaster69-dev <rathore6375@gmail.com>